image: Visual Studio 2019
branches:
  only:
  - master
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build
test_script:
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByFile="**/PlatformAbstractions.cs" Versionize.Tests/Versionize.Tests.csproj
deploy: off
